# Generated by Django 5.0.3 on 2024-05-17 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_remove_item_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issueitem',
            name='amount',
        ),
    ]
