# Generated by Django 5.0.3 on 2024-05-17 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_remove_issueitem_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='date_updated',
        ),
    ]
