# Generated by Django 5.0.3 on 2024-05-17 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_remove_item_date_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='status',
        ),
    ]
