# Generated by Django 5.0.3 on 2024-05-17 12:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_remove_item_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='returnitem',
            name='all_returned',
        ),
        migrations.RemoveField(
            model_name='returnitem',
            name='returned_amount',
        ),
        migrations.AlterField(
            model_name='returnitem',
            name='returned_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
