# Generated by Django 5.0.3 on 2024-05-17 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_remove_returnitem_all_returned_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RestockItem',
        ),
    ]
